---
title: "Descriptive data analysis"
author: "Luke Qian"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```

## Load packages
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
```


## Data preparation
```{r, message=FALSE}
# load the datasets
farmSurvey = read_csv("Data/Farm Survey Data.csv")
microTest = read_csv("Data/Raw Milk Micro Data.csv")

# merge the datasets
dat = merge(farmSurvey, microTest, by = c("FarmID", "Sampling"))

# simplify column names
names(dat) = c("FarmID", "Sampling", "Loc", "University", "CertYear", "HouseStyle", 
               "PastureTime", "StallNumPerArea", "CowNumPerArea", "StockDen", "Bedding", 
               "BedAdd","BedAddFreq", "StallCleanFreq", "CowNum", "MilkFreq", "PplNumPerWk",
               "PplNumPerShift", "NonFamEmp", "NonFamEmpNum", "FullEmp", "FullEmpNum",
               "PartEmp", "PartEmpNum", "Glove", "GloveFreq", "PreDip", "PreDipType",
               "PostDip", "PostDipType", "UdderSti", "ClipFlame", "CowMilkLoc", "Parlor",
               "ParlorClean", "CowParlorClean", "CowWaitMilk", "HoldClean", "CowHoldClean",
               "TeatEndScore", "TeatPercent3to4", "UdderHygScore", "UdderPercent3to4",
               "TowelType", "TowelCleanProto", "CowTowelWipe", "CornSilage", "Haylage",
               "CornMeal", "DryHay", "Baleage", "GrassSillage", "Earlage", "Snaplage",
               "OtherFeed", "BioFeedAdd", "DryMatPercent", "FeedPurchase", "Coop",
               "ClosedHerd","FarmIDNum", "Test", "GreaterLess", "UneditConc", "Conc",
               "Notes")

# modify specific data entries
## 1) stocking density
dat = dat %>% mutate(StockDen = ifelse(StockDen == "BEDDED PACK" | 
                                         StockDen == "PASTURE" |
                                         StockDen == "DRY LOT", 0, StockDen))
### check "#VALUE!"
#dat %>% 
#  filter(StockDen == "#VALUE!") %>% 
#  select(c(StallNumPerArea, CowNumPerArea, StockDen))

dat[dat$StockDen == "#VALUE!",]$StockDen = c( (90+95)/2/75*100, (90+95)/2/75*100, (90+95)/2/75*100,
                       (250+200)/2/800*100, (250+200)/2/800*100, (250+200)/2/800*100, (250+200)/2/800*100,
                       0, 0, 0, 0, 0, 0, 0,
                       (100+125)/2/375*100, (100+125)/2/375*100, (100+125)/2/375*100, (100+125)/2/375*100,
                       (95+180+240+260)/4/375*100, (95+180+240+260)/4/375*100, (95+180+240+260)/4/375*100, (95+180+240+260)/4/375*100,
                       mean(c(97, 400, 400, 38))/375*100, mean(c(97, 400, 400, 38))/375*100, mean(c(97, 400, 400, 38))/375*100,
                       mean(c(95, 385, 400, 70, 25, 20))/375*100, mean(c(95, 385, 400, 70, 25, 20))/375*100,
                       mean(c(95, 385, 400, 70, 25, 20))/375*100, mean(c(95, 385, 400, 70, 25, 20))/375*100,
                       mean(c(105, 105, 367, 368))/375*100, mean(c(105, 105, 367, 368))/375*100, mean(c(105, 105, 367, 368))/375*100
                       )
## 2) Cow number
dat = dat %>% mutate(CowNum = ifelse(CowNum == "??", NA, CowNum))

## 3) full employee number
dat = dat %>% mutate(FullEmpNum = ifelse(FullEmpNum == "3 family tend to robots", 0, FullEmpNum))

## 4) Cows wiped with individual towels
dat = dat %>% mutate(CowTowelWipe = ifelse(CowTowelWipe == "robotic milker", 0, CowTowelWipe))

## 5) Percentage of dry matter
dat = dat %>% 
  mutate(DryMatPercent = ifelse(DryMatPercent %in% c("31-40%", "0-10%", "21-30%", "11-20%"), "< 40%", DryMatPercent)) %>% 
  mutate(DryMatPercent = ifelse(DryMatPercent %in% c("41-50%", "51-60%", "61-70%", "> 40%"), "40-70%", DryMatPercent)) %>% 
  mutate(DryMatPercent = ifelse(DryMatPercent == ">70%", "> 70%", DryMatPercent))

## 6) Test
dat = dat %>% mutate(Test = ifelse(Test == "MSC`", "MSC", Test))

## 7) The frequency of adding bedding
dat = dat %>% mutate(BedAddFreq = ifelse(BedAddFreq == "<1x/day", "< 1x per day", BedAddFreq))

# change data type
dat = dat %>% mutate(StockDen = round(as.numeric(sub("%", "", StockDen))/100 ,2),
                     CowNum = as.numeric(CowNum),  
                     FullEmpNum = as.numeric(FullEmpNum),
                     CowTowelWipe = as.numeric(CowTowelWipe))

# make sure all questions have more than one answer
#dat %>% sapply(., function(x) length(unique(x))) 
```

## Descriptive analysis
```{r}
for (i in 1:60){
  var = names(dat)[i]
  if (!(var %in% c("StallNumPerArea", "CowNumPerArea","OtherFeed"))){
    
    ## Categorical variables
    if (class(dat[[var]]) != "numeric"){
          plot = ggplot(data = dat, aes(x = .data[[var]], y = log10(Conc+0.01), fill = .data[[var]]))+
            geom_boxplot()+
            facet_wrap(~Test)+
            theme_bw()+
            theme(axis.text.x=element_blank(),
                  axis.ticks.x=element_blank())
          
    ## Numeric variables
    } else {
          plot = ggplot(data = dat, aes(x = .data[[var]], y = log10(Conc+0.01)))+
            geom_point()+
            facet_wrap(~Test)+
            theme_bw()
    }
    paste0("Summary plots/", var, ".tiff", by="") %>% ggsave()
  }
}



```

